[project]
name = "qml-dpg-2026"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "marimo>=0.23.9",
    "nbformat>=5.10.4",
    "qiskit==2.1.2",
    "quimb>=1.14.0",
    "scikit-learn>=1.9.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "matplotlib==3.11.0",
    "pennylane==0.45.0",
    "pennylane-lightning==0.45.0",
    "pennylane-lightning-gpu==0.45.0",
    "pennylane-lightning-tensor==0.45.0",
    "pylatexenc==2.10",
    "qiskit-algorithms==0.4.0",
    "qiskit-aer>=0.17.2",
    "seaborn>=0.13.2",
    "qiskit-machine-learning>=0.9.0",
    "iqm-client[qiskit]==35.0.1",
    "iqm-qubit-selector==1.1.1",
    "mitiq==1.0.0",
    "numpy==2.2.6",
    "squlearn>=0.11.2",
]
